architecture:
    backbone: openai/whisper-base.en
    freeze_encoder: false
    gradient_checkpointing: false
    language: en
    pretrained: true
audio:
    sample_rate: 16000
augmentation: {}
dataset:
    audio_column: file
    data_folder: data/user/commands_speech_recognition/commands/
    data_folder_test: None
    data_sample: 1.0
    data_sample_choice:
    - Train
    - Validation
    group_fold_column: file
    label_columns: transcript
    selected_folds:
    - '4'
    test_dataframe: None
    train_dataframe: data/user/commands_speech_recognition/commands.csv
    validation_dataframe: None
    validation_size: 0.2
    validation_strategy: kfold
environment:
    gpus:
    - '0'
    mixed_precision_inference: false
    mixed_precision_training: true
    number_of_seeds_per_run: 1
    number_of_workers: 4
    seed: -1
experiment_name: 66_commands_speech_recognition
logging:
    log_grad_norm: false
    logger: None
    neptune_project: ''
    number_of_audios: 8
prediction:
    duration_in_visualizations: 60
    metric: WER
    normalize_text: true
    suppress_default_tokens: false
training:
    automatically_adjust_batch_size: false
    batch_size: 1
    build_scoring_pipelines: true
    calculate_train_metric: false
    drop_last_batch: true
    epochs: 3
    evaluate_before_training: true
    evaluation_epochs: 1
    grad_accumulation: 1
    gradient_clip: 0.0
    learning_rate: 1.0e-05
    optimizer: AdamW
    save_best_checkpoint: false
    schedule: Cosine
    train_validation_data: false
    warmup_epochs: 0
    weight_decay: 0.0
