architecture:
    backbone: distilbert-base-cased-distilled-squad
    gradient_checkpointing: false
    intermediate_dropout: 0.0
    pretrained: true
augmentation:
    token_mask_probability: 0.0
dataset:
    answer_column: answer
    answer_start_column: None
    context_column: context
    data_sample: 1.0
    data_sample_choice:
    - Train
    - Validation
    group_fold_column: question
    number_of_predicted_answers: 3
    question_column: question
    selected_folds:
    - '0'
    test_dataframe: None
    train_dataframe: data/user/sql-create-context/sql-create-context.csv
    validation_dataframe: None
    validation_size: 0.2
    validation_strategy: kfold
environment:
    gpus:
    - '0'
    mixed_precision_inference: false
    mixed_precision_training: true
    number_of_seeds_per_run: 1
    number_of_workers: 4
    seed: -1
experiment_name: 80_sql-create-context
logging:
    log_grad_norm: false
    logger: None
    neptune_project: ''
    number_of_texts: 10
prediction:
    metric: Jaccard
tokenizer:
    doc_stride: 64
    lowercase: false
    max_length: 256
training:
    automatically_adjust_batch_size: false
    batch_size: 16
    build_scoring_pipelines: true
    calculate_train_metric: false
    differential_learning_rate: 1.0e-05
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 2
    evaluate_before_training: true
    evaluation_epochs: 1
    grad_accumulation: 1
    gradient_clip: 0.0
    learning_rate: 1.0e-05
    loss_function: CrossEntropy
    optimizer: AdamW
    save_best_checkpoint: false
    schedule: Cosine
    train_validation_data: false
    warmup_epochs: 0
    weight_decay: 0.0
