architecture:
    backbone: distilbert-base-uncased
    dropout: 0
    embedding_size: 512
    gradient_checkpointing: false
    intermediate_dropout: 0.0
    pool: Average
    pretrained: true
augmentation: {}
dataset:
    data_sample: 1
    data_sample_choice:
    - Train
    - Validation
    folds:
    - '4'
    group_fold_column: text
    label_columns: label
    separator: ''
    test_dataframe: data/anon/ubuntu_text_metric_learning/test.csv
    text_column:
    - text
    train_dataframe: data/anon/ubuntu_text_metric_learning/train.csv
    validation_dataframe: None
    validation_size: 0.2
    validation_strategy: kfold
environment:
    gpus:
    - '0'
    mixed_precision_inference: false
    mixed_precision_training: true
    number_of_workers: 4
    seed: -1
experiment_name: 63_ubuntu_text_metric_learning
logging:
    logger: None
    neptune_project: ''
    number_of_texts: 10
prediction:
    metric: mAP
    top_k_similar: 50
tokenizer:
    lowercase: false
    max_length: 128
    padding_quantile: 1.0
training:
    arcface_margin: 0.1
    arcface_scale: 45
    automatically_adjust_batch_size: false
    batch_size: 16
    build_scoring_pipelines: true
    calculate_train_metric: false
    differential_learning_rate: 0.0001
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 5
    evaluation_epochs: 1
    grad_accumulation: 1
    gradient_clip: 0.0
    learning_rate: 0.0001
    loss_function: ArcFace
    optimizer: AdamW
    save_best_checkpoint: false
    schedule: Cosine
    train_validation_data: false
    warmup_epochs: 0
    weight_decay: 0.0
